# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleChat

  target 'SimpleChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Qiscus'
  end

  target 'SimpleChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
